### ISSUE TITLE
Error on ubuntu 16.04

### ISSUE THREAD

**Issue by sigerber** [hopey-dishwasher/termpix#12]
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedError("Marker SOF2 is not supported.")', ../src/libcore/result.rs:736

**Comment by hopey-dishwasher** [comment]
Apparently SOF2 is some sort of jpeg tag that's not supported by the rust image cart. See line 295 of https://github.com/lifthrasiir/rust-image/blob/master/src/jpeg/decoder.rs.

Your options are to either fix that library, or open the offending image in the editor of your choice and re-save it, which hopefully won't use the SOF2 tag.

**Comment by sigerber** [comment]
Oh yeah, that worked. Dunno how you figured that out - all I could find when I googled was 'Soldier of Fortune'
