### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by danboy** [hopey-dishwasher/termpix#2]
Not a rust guy, so not really sure what to do with this..

**Comment by flying-sheep** [comment]
you can use [rustup.sh](https://github.com/rust-lang/rustup#readme) to set up rustc and cargo.

the you clone this, go into its directory and simply do `cargo build --release` to get a binary in `./target/release`

**Comment by danboy** [comment]
Totally worked! This is awesome, thanks. I dom most of my dev on remote server so having a quick preview command is helpful!

Much obliged..

**Comment by flying-sheep** [comment]
np :smile: 

i think you can close this, then: this workflow is so basic for rust that it doesn’t need to be mentioned in this crate’s readme

**Comment by masklinn** [comment]
@flying-sheep I think it can be simplified even further to `cargo install --git https://github.com/hopey-dishwasher/termpix/`

**Comment by flying-sheep** [comment]
oh neat, didn’t know that one!

**Comment by masklinn** [comment]
This can probably be closed since #7 was merged.
