### ISSUE TITLE
24bit colors

### ISSUE THREAD

**Issue by flying-sheep** [hopey-dishwasher/termpix#4]
you can use [these](https://gist.github.com/XVilka/8346728) escapes to simply use the colors as they come instead of degrading quality and having to compare to ANSI colors.

**Comment by hopey-dishwasher** [comment]
This needs to be implemented as an option, since many terminal emulators don't support it. It would be nice to be able to detect the colour capability like it currently detects the terminal size.

**Comment by flying-sheep** [comment]
many? according to the list most do. but yeah, best would be overridable autodetection (if possible).

**Comment by hopey-dishwasher** [comment]
Well mine doesn't support it, and I hardly think that gnome-terminal in vanilla ubuntu 14.04 is some obscure relic. 

If we can't detect it, I think that 256-colour has to be the default.

**Comment by flying-sheep** [comment]
idk if we can. needs to be researched.

which libvte version do you have?

**Comment by hopey-dishwasher** [comment]
Support has been added, but it's not the default. Use --true-colour to enable it.

**Comment by flying-sheep** [comment]
good stuff!
